import React from 'react';
import { Document, Page, Text, View, StyleSheet, Font } from '@react-pdf/renderer';

// Register a standard font if needed, or rely on defaults (Helvetica/Times)
// For "Serif", Times-Roman is standard in PDF.

const styles = StyleSheet.create({
    page: {
        padding: 50, // 1 inch margins approx
        fontFamily: 'Times-Roman',
        fontSize: 12,
        lineHeight: 1.5,
        backgroundColor: '#FFFFFF', // A4 Paper White
    },
    header: {
        marginBottom: 20,
        textAlign: 'center',
    },
    brand: {
        fontSize: 10,
        color: '#D4AF37', // Divine Gold
        letterSpacing: 2,
        textTransform: 'uppercase',
        marginBottom: 5,
        fontFamily: 'Times-Bold',
    },
    title: {
        fontSize: 24,
        color: '#000000',
        fontFamily: 'Times-Bold',
        marginBottom: 20,
        textAlign: 'center',
    },
    scriptureBox: {
        marginBottom: 20,
        paddingLeft: 15,
        borderLeftWidth: 3,
        borderLeftColor: '#D4AF37', // Divine Gold
    },
    scriptureText: {
        fontFamily: 'Times-Italic',
        fontSize: 14,
        color: '#333333',
    },
    content: {
        marginTop: 10,
        textAlign: 'justify',
        color: '#1a1a1a',
        minHeight: 300,
    },
    footer: {
        position: 'absolute',
        bottom: 30,
        left: 0,
        right: 0,
        textAlign: 'center',
        fontSize: 9,
        color: '#888888',
        borderTopWidth: 1,
        borderTopColor: '#EEEEEE',
        paddingTop: 10,
        marginHorizontal: 50,
    },
});

interface SermonPdfTemplateProps {
    title?: string;
    scripture?: string;
    content?: string;
}

export const SermonPdfTemplate = ({ title, scripture, content }: SermonPdfTemplateProps) => (
    <Document>
        <Page size="A4" style={styles.page}>

            {/* Header */}
            <View style={styles.header}>
                <Text style={styles.brand}>Rhema AI</Text>
            </View>

            {/* Main Content */}
            <Text style={styles.title}>{title || "Untitled Sermon"}</Text>

            {(scripture) && (
                <View style={styles.scriptureBox}>
                    <Text style={styles.scriptureText}>“{scripture}”</Text>
                </View>
            )}

            <Text style={styles.content}>
                {content || "Start typing your sermon notes..."}
            </Text>

            {/* Footer */}
            <View style={styles.footer}>
                <Text>Generated by RhemaAI • Divine Intelligence</Text>
            </View>

        </Page>
    </Document>
);
